title: DENOG e.V.
baseurl: "" # the subpath of your site, e.g. /blog
markdown: kramdown
env: "production"
url: https://www.denog.de

exclude: ['_theme', package.json, Gemfile, Gemfile.lock, '.idea', '.travis.yml', 'vendor']
include: ['.well-known', 'files/board_meetings']

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "files/board_meetings"
    values:
      board_meeting: true
